### ISSUE TITLE
Segmentation of blobs.tif

### ISSUE THREAD

**Issue by haesleinhuepf** [4DNucleome/PartSeg#403]
Hi @Czaki ,

I'm trying to segment [blobs.tif](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/data/blobs.tif) and don't manage. In other tools, Otsu-Thresholding typically does the job. In Partseg, I get an empty layer:
![image](https://user-images.githubusercontent.com/12660498/137326127-2a65c6a9-0f4b-4eed-a685-5d023cf9f17f.png).

Also, there are quite some options for segmentation. Is there some user-documentation of how to segment an image with the partseg napari plugin?

Thanks!

Best,
Robert

**Comment by Czaki** [comment]
PartSeg was created for 3d images and its default parameter are set for 3d images. 

As I check the largest object on this image (using otsu tresholding) has a size of 902 pixels.  
So if you change "minimum size" to be below these values (for example 100) then You will see the results. 

There is a proper message emitted by the algorithm and I will add propagation to the napari interface in a short time.

![Zrzut ekranu z 2021-10-14 15-38-26](https://user-images.githubusercontent.com/3826210/137328864-7835c344-a2c9-434e-9607-23c460512272.png)

**Comment by haesleinhuepf** [comment]
That error message is very helpful! Thanks 👍
