### ISSUE TITLE
Search Label widget does not always work

### ISSUE THREAD

**Issue by Karol-G** [4DNucleome/PartSeg#536]
Hi,

it seems that the Search Label widget only works if the mask has been generated with another PartSeg widget before. For example, it is not possible to simply create a label layer or load a label layer and then use the Search Label widget on it.
In this case the ROI field does not display any available layers.

Best,
Karol

**Comment by Karol-G** [comment]
Ah, it is working now. I was still using an older dev version of 0.4.14. I reinstalled the stable 0.4.14 and everthing is working now as intended. Thanks for the help :)

Best,
Karol

**Comment by Czaki** [comment]
Yes, there was such a bug in napari some time ago between versions.
